name: base
channels:
  - gurobi
  - pytorch
  - conda-forge
  - https://conda.anaconda.org/gurobi
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - anyio=3.5.0=py38h06a4308_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - argon2-cffi=20.1.0=py38h27cfd23_1
  - asttokens=2.0.5=pyhd3eb1b0_0
  - attrs=21.4.0=pyhd3eb1b0_0
  - babel=2.11.0=py38h06a4308_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.11.1=py38h06a4308_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - boltons=23.0.0=py38h06a4308_0
  - bottleneck=1.3.5=py38h7deecbd_0
  - brotli=1.0.9=he6710b0_2
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2023.08.22=h06a4308_0
  - certifi=2023.7.22=py38h06a4308_0
  - cffi=1.14.0=py38he30daa8_1
  - chardet=3.0.4=py38_1003
  - conda=23.3.1=py38h06a4308_0
  - conda-package-handling=1.6.1=py38h7b6447c_0
  - cryptography=2.9.2=py38h1ba5d50_0
  - cudatoolkit=11.6.0=hecad31d_10
  - cycler=0.11.0=pyhd3eb1b0_0
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.5.1=py38h295c915_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.4=py38h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.4.4=h295c915_0
  - ffmpeg=4.3=hf484d3e_0
  - fontconfig=2.13.1=h6c09931_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.11.0=h70c0345_0
  - giflib=5.2.1=h36c2ea0_2
  - glib=2.69.1=h4ff587b_1
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - gurobi=10.0.3=py38_0
  - icu=58.2=he6710b0_3
  - idna=2.9=py_1
  - importlib_resources=5.2.0=pyhd3eb1b0_1
  - intel-openmp=2021.4.0=h06a4308_3561
  - ipykernel=6.15.2=py38h06a4308_0
  - ipython=8.4.0=py38h06a4308_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.5=pyhd3eb1b0_1
  - jbig=2.1=h7f98852_2003
  - jedi=0.18.1=py38h06a4308_1
  - jinja2=3.0.3=pyhd3eb1b0_0
  - jpeg=9e=h166bdaf_1
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonpatch=1.32=pyhd3eb1b0_0
  - jsonpointer=2.1=pyhd3eb1b0_0
  - jsonschema=4.4.0=py38h06a4308_0
  - jupyter=1.0.0=py38h06a4308_8
  - jupyter_client=7.2.2=py38h06a4308_0
  - jupyter_console=6.4.3=pyhd3eb1b0_0
  - jupyter_core=4.10.0=py38h06a4308_0
  - jupyter_server=1.23.4=py38h06a4308_0
  - jupyterlab=3.5.3=py38h06a4308_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.10.3=pyhd3eb1b0_1
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - kiwisolver=1.4.2=py38h295c915_0
  - lame=3.100=h7f98852_1001
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - lerc=2.2.1=h9c3ff4c_0
  - libdeflate=1.7=h7f98852_5
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.3=he6710b0_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.17=h166bdaf_0
  - libpng=1.6.37=h21135ba_2
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=12.1.0=ha89aaad_16
  - libtiff=4.3.0=hf544144_1
  - libuuid=1.0.3=h7f8727e_2
  - libwebp=1.2.2=h3452ae3_0
  - libwebp-base=1.2.2=h7f98852_1
  - libxcb=1.15=h7f8727e_0
  - libxml2=2.9.12=h03d6c58_0
  - lz4-c=1.9.3=h9c3ff4c_1
  - markupsafe=2.1.1=py38h7f8727e_0
  - matplotlib=3.5.1=py38h06a4308_1
  - matplotlib-base=3.5.1=py38ha18d171_1
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mistune=0.8.4=py38h7b6447c_1000
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h95df7f1_0
  - mkl_fft=1.3.1=py38h8666266_1
  - mkl_random=1.2.2=py38h1abd341_0
  - munkres=1.1.4=py_0
  - nbclassic=0.5.2=py38h06a4308_0
  - nbclient=0.5.13=py38h06a4308_0
  - nbconvert=6.4.4=py38h06a4308_0
  - nbformat=5.3.0=py38h06a4308_0
  - ncurses=6.2=he6710b0_1
  - nest-asyncio=1.5.5=py38h06a4308_0
  - nettle=3.6=he412f7d_0
  - notebook=6.5.2=py38h06a4308_0
  - notebook-shim=0.2.2=py38h06a4308_0
  - numexpr=2.8.4=py38he184ba9_0
  - numpy=1.22.3=py38he7a7128_0
  - numpy-base=1.22.3=py38hf524024_0
  - openh264=2.1.1=h780b84a_0
  - openssl=1.1.1w=h7f8727e_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - patsy=0.5.3=py38h06a4308_0
  - pcre=8.45=h295c915_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.0.1=py38h22f2fdc_0
  - pip=20.0.2=py38_3
  - pluggy=1.0.0=py38h06a4308_1
  - pooch=1.4.0=pyhd3eb1b0_0
  - prometheus_client=0.13.1=pyhd3eb1b0_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - prompt_toolkit=3.0.20=hd3eb1b0_0
  - psutil=5.9.0=py38h5eee18b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycosat=0.6.3=py38h7b6447c_1
  - pycparser=2.20=py_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pyopenssl=19.1.0=py38_0
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - pyqt=5.9.2=py38h05f1152_4
  - pyrsistent=0.18.0=py38heee7806_0
  - pysocks=1.7.1=py38_0
  - python=3.8.3=hcff3b4d_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.15.1=pyhd3eb1b0_0
  - python_abi=3.8=2_cp38
  - pytorch-mutex=1.0=cuda
  - pyzmq=23.2.0=py38h6a678d5_0
  - qt=5.9.7=h5867ecd_1
  - qtconsole=5.3.1=py38h06a4308_0
  - qtpy=2.0.1=pyhd3eb1b0_0
  - readline=8.0=h7b6447c_0
  - requests=2.23.0=py38_0
  - ruamel.yaml=0.17.21=py38h5eee18b_0
  - ruamel.yaml.clib=0.2.6=py38h5eee18b_1
  - ruamel_yaml=0.15.87=py38h7b6447c_0
  - seaborn=0.12.2=py38h06a4308_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=46.4.0=py38_0
  - sip=4.19.13=py38h295c915_0
  - six=1.14.0=py38_0
  - sniffio=1.2.0=py38h06a4308_1
  - soupsieve=2.3.1=pyhd3eb1b0_0
  - sqlite=3.31.1=h62c20be_1
  - stack_data=0.2.0=pyhd3eb1b0_0
  - statsmodels=0.13.5=py38h7deecbd_1
  - terminado=0.13.1=py38h06a4308_0
  - testpath=0.6.0=py38h06a4308_0
  - tk=8.6.8=hbc83047_0
  - tomli=2.0.1=py38h06a4308_0
  - toolz=0.12.0=py38h06a4308_0
  - torchaudio=0.12.0=py38_cu116
  - torchvision=0.13.0=py38_cu116
  - tornado=6.1=py38h27cfd23_0
  - tqdm=4.46.0=py_0
  - traitlets=5.1.1=pyhd3eb1b0_0
  - typing_extensions=4.3.0=pyha770c72_0
  - urllib3=1.25.8=py38_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py38_1
  - websocket-client=0.58.0=py38h06a4308_4
  - wheel=0.34.2=py38_0
  - widgetsnbextension=3.5.2=py38h06a4308_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.1.7=had09818_2
  - zeromq=4.3.4=h2531618_0
  - zipp=3.8.0=py38h06a4308_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.5.0=ha95c52a_0
  - pip:
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.10.11
      - aiosignal==1.3.1
      - async-timeout==5.0.1
      - cartopy==0.21.1
      - cftime==1.6.2
      - click==8.1.7
      - click-plugins==1.1.1
      - cligj==0.7.2
      - cmake==3.27.1
      - creme==0.6.1
      - cvxopt==1.3.0
      - cvxpy==1.2.0
      - cvxpylayers==0.1.6
      - dashscope==1.24.2
      - diffcp==1.0.22
      - dill==0.3.7
      - ecos==2.0.12
      - et-xmlfile==1.1.0
      - filelock==3.12.2
      - fiona==1.9.5
      - frozenlist==1.5.0
      - geopandas==0.13.2
      - gurobipy==10.0.1
      - importlib-metadata==6.8.0
      - joblib==1.2.0
      - lit==16.0.6
      - mmh3==2.5.1
      - mpmath==1.3.0
      - multidict==6.1.0
      - multimethod==1.10
      - multiprocess==0.70.15
      - narwhals==1.42.1
      - netcdf4==1.6.3
      - networkx==3.1
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - openpyxl==3.1.1
      - osqp==0.6.2.post8
      - pandas==1.5.3
      - pathos==0.3.1
      - pendulum==2.1.2
      - ply==3.11
      - pox==0.3.3
      - ppft==1.7.6.7
      - propcache==0.2.0
      - pybind11==2.10.4
      - pyepo==0.3.3
      - pymorton==1.0.5
      - pyomo==6.6.1
      - pyproj==3.5.0
      - pyshp==2.3.1
      - pytz==2022.7.1
      - pytzdata==2020.1
      - qdldl==0.1.5.post3
      - rsome==1.3.1
      - salib==1.4.7
      - scikit-learn==1.2.2
      - scipy==1.10.1
      - scs==3.2.2
      - shapely==2.0.1
      - sklearn==0.0.post4
      - sklearn-contrib-py-earth==0.1.0+16.g400f84d
      - sympy==1.12
      - threadpoolctl==3.1.0
      - torch==2.0.1
      - triton==2.0.0
      - xgboost==1.7.5
      - yarl==1.15.2
prefix: /home/zyz/miniconda3
